const categories = [
  { "name": "Frutas" },
  { "name": "Vegetais" },
  { "name": "Carnes" },
  { "name": "Aves" },
  { "name": "Peixes" },
  { "name": "Frutos do Mar" },
  { "name": "Lacteos" },
  { "name": "Achocolatados" },
  { "name": "Ovos" },
  { "name": "Panificação" },
  { "name": "Cereais e Grãos" },
  { "name": "Massas" },
  { "name": "Molhos" },
  { "name": "Veganos" },
  { "name": "Vegetarianos" },
  { "name": "Enlatados e Conservas" },
  { "name": "Snacks e Salgadinhos" },
  { "name": "Sobremesas e Doces" },
  { "name": "Bebidas Alcoólicas" },
  { "name": "Bebidas Não Alcoólicas" },
  { "name": "Refrigerantes" },
  { "name": "Café, Chá e Infusões" },
  { "name": "Condimentos e Temperos" },
  { "name": "Óleos e Vinagres" },
  { "name": "Limpeza" },
  { "name": "Higiene Pessoal" },
  { "name": "Artigos para Cuidados com o Bebê" },
  { "name": "Produtos para Animais de Estimação" },
  { "name": "Papelaria e Escritório" },
  { "name": "Utensílios de Cozinha" },
  { "name": "Artigos de Limpeza Doméstica" },
  { "name": "Cuidados com a Roupa" },
  { "name": "Cuidados com o Cabelo" },
  { "name": "Cuidados com a Pele" },
  { "name": "Higiene Oral" },
  { "name": "Suplementos Alimentares" },
  { "name": "Saúde e Bem-estar" },
  { "name": "Cuidados Pessoais" },
  { "name": "Artigos de Cuidados para Idosos" },
  { "name": "Outros" }
]

export default categories;
