const categories = [
  { "name": "Frutas", "icon": "🍇" },
  { "name": "Vegetais", "icon": "🥦" },
  { "name": "Carnes", "icon": "🥩" },
  { "name": "Aves", "icon": "🦢" },
  { "name": "Peixes", "icon": "🐟" },
  { "name": "Frutos do Mar", "icon": "🦐" },
  { "name": "Lacteos", "icon": "🥛" },
  { "name": "Achocolatados", "icon": "🍫" },
  { "name": "Ovos", "icon": "🥚" },
  { "name": "Panificação", "icon": "🍞" },
  { "name": "Cereais e Grãos", "icon": "🌾" },
  { "name": "Massas", "icon": "🍝" },
  { "name": "Molhos", "icon": "🍅" },
  { "name": "Veganos", "icon": "🌱" },
  { "name": "Vegetarianos", "icon": "🥗" },
  { "name": "Enlatados e Conservas", "icon": "🥫" },
  { "name": "Snacks e Salgadinhos", "icon": "🍿" },
  { "name": "Sobremesas e Doces", "icon": "🍰" },
  { "name": "Bebidas Alcoólicas", "icon": "🍷" },
  { "name": "Bebidas Não Alcoólicas", "icon": "🥤" },
  { "name": "Refrigerantes", "icon": "🥤" },
  { "name": "Café, Chá e Infusões", "icon": "☕" },
  { "name": "Condimentos e Temperos", "icon": "🧂" },
  { "name": "Óleos e Vinagres", "icon": "🍶" },
  { "name": "Limpeza", "icon": "🧼" },
  { "name": "Higiene Pessoal", "icon": "🛀" },
  { "name": "Artigos para Cuidados com o Bebê", "icon": "🍼" },
  { "name": "Produtos para Animais de Estimação", "icon": "🐾" },
  { "name": "Papelaria e Escritório", "icon": "📚" },
  { "name": "Utensílios de Cozinha", "icon": "🍴" },
  { "name": "Artigos de Limpeza Doméstica", "icon": "🧽" },
  { "name": "Cuidados com a Roupa", "icon": "👗" },
  { "name": "Cuidados com o Cabelo", "icon": "💇" },
  { "name": "Cuidados com a Pele", "icon": "🧴" },
  { "name": "Higiene Oral", "icon": "🦷" },
  { "name": "Suplementos Alimentares", "icon": "💊" },
  { "name": "Saúde e Bem-estar", "icon": "🏥" },
  { "name": "Cuidados Pessoais", "icon": "🧴" },
  { "name": "Artigos de Cuidados para Idosos", "icon": "👵" },
  { "name": "Outros", "icon": "📦" }
];

export default categories;
